/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ai/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 调用大模型进行对话
         * @description 当 stream=true 时以 SSE 推送返回；否则返回完整 JSON。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChatRequest"];
                    "multipart/form-data": {
                        /** @description JSON 字符串的 messages 数组 */
                        messages: string;
                        /**
                         * Format: binary
                         * @description 图片文件（type=image 时可用）
                         */
                        image?: string;
                        model?: string;
                        stream?: boolean;
                        sessionId?: number;
                        lang?: string;
                    };
                };
            };
            responses: {
                /** @description 非流式模式响应 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatResponse"];
                        "text/event-stream": components["schemas"]["StreamChunk"];
                    };
                };
                /** @description 参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description AI 服务错误 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/chat-mock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mock SSE 流，便于前端调试 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @default true */
                        stream?: boolean;
                        sessionId?: number;
                    };
                };
            };
            responses: {
                /** @description 返回 mock 数据或开启 SSE */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatResponse"];
                        "text/event-stream": components["schemas"]["StreamChunk"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前用户的会话列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            sessions?: components["schemas"]["Session"][];
                        };
                    };
                };
                /** @description 未认证 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/sessions/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取指定会话的消息记录 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 会话 ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            messages?: components["schemas"]["Message"][];
                        };
                    };
                };
                /** @description 未认证 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/sessions/{id}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 删除会话及其消息 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 要删除的会话 ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 删除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 未认证 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 会话不存在或无权限 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取可用模型列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 获取失败 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/messages/{id}/like": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 点赞或取消点赞消息 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 消息 ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 操作成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LikeResponse"];
                    };
                };
                /** @description 未认证 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 消息不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/messages/{id}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重新生成指定 AI 消息 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 需要重生成的消息 ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RegenerateRequest"];
                };
            };
            responses: {
                /** @description 非流式刷新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 未认证 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 消息不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 重生成失败 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/speech-to-text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 语音识别（基于本地 whisper.cpp） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description 音频文件（wav、mp3）
                         */
                        audio: string;
                    };
                };
            };
            responses: {
                /** @description 识别成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpeechToTextResponse"];
                    };
                };
                /** @description 未提供音频 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 识别失败 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/speech-upload/chunk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 上传音频分片（支持断点续传） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** @description 客户端生成的文件唯一标识 */
                        fileId: string;
                        /** @description 分片序号（从 0 开始） */
                        chunkIndex: number;
                        /** @description 分片总数 */
                        totalChunks: number;
                        /**
                         * Format: binary
                         * @description 当前分片内容
                         */
                        chunk: string;
                    };
                };
            };
            responses: {
                /** @description 分片上传成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpeechChunkResponse"];
                    };
                };
                /** @description 参数或分片文件错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/speech-to-text/stream/{fileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 实时转写已上传的音频（SSE）
         * @description 建立 SSE 连接，服务端会持续返回 partial/done 事件。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 上传时使用的文件 ID */
                    fileId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description text/event-stream，包含实时转写内容 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": components["schemas"]["SpeechStreamEvent"];
                    };
                };
                /** @description 文件未找到 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 微信登录并创建/更新用户信息 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description 登录成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                /** @description 参数错误或微信接口返回错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 服务器内部错误 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/login/h5": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** H5 账号密码登录（不存在则自动注册） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["H5LoginRequest"];
                };
            };
            responses: {
                /** @description 登录成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                /** @description 参数错误或微信接口返回错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 服务器内部错误 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前登录用户信息 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 获取成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 获取成功 */
                            msg?: string;
                            user?: components["schemas"]["UserInfo"];
                        };
                    };
                };
                /** @description 未认证或 token 失效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 用户不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 刷新 token（需在旧 token 未过期时调用） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 刷新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                /** @description 未认证或 token 失效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChatMessage: {
            /**
             * @description 消息类型（image 会进行 OCR 识别）
             * @enum {string}
             */
            type?: "text" | "image" | "audio";
            /** @enum {string} */
            role: "user" | "assistant" | "system";
            /** @description 消息正文（text 消息必填） */
            content?: string;
            /** @description 图片 URL（type=image 时可用） */
            imageUrl?: string;
            /** @description 图片 base64（type=image 时可用） */
            imageBase64?: string;
            /** @description 音频 URL（type=audio 时可用） */
            audioUrl?: string;
            /** @description 音频 base64（type=audio 时可用） */
            audioBase64?: string;
            /** @description 图片识别后的追加提问 */
            prompt?: string;
            /** @description OCR 语言（默认 chi_sim） */
            lang?: string;
        };
        ChatRequest: {
            messages: components["schemas"]["ChatMessage"][];
            /** @description OCR 默认语言（可选） */
            lang?: string;
            /** @example deepseek-chat */
            model?: string;
            /** @default true */
            stream: boolean;
            sessionId?: number | null;
        };
        ChatResponse: {
            sessionId?: number;
            reply?: {
                /** @example assistant */
                role?: string;
                content?: string;
            };
        };
        StreamChunk: {
            /** @enum {string} */
            type?: "delta" | "thinking" | "done";
            text?: string;
            thinking?: string;
            sessionId?: number;
        };
        Session: {
            id?: number;
            title?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        Message: {
            id?: number;
            role?: string;
            /** @enum {string} */
            type?: "text" | "image" | "audio";
            /** @description 媒体内容（图片/音频的 URL 或 dataURL） */
            media?: string;
            content?: string;
            reasoning_content?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** @enum {integer} */
            liked?: 0 | 1;
        };
        RegenerateRequest: {
            /** @default true */
            stream: boolean;
            /** @example deepseek-chat */
            model?: string;
        };
        LikeResponse: {
            msg?: string;
            messageId?: number;
            /** @enum {integer} */
            liked?: 0 | 1;
        };
        SpeechToTextResponse: {
            /** @example 语音识别成功 */
            msg?: string;
            text?: string;
        };
        SpeechChunkResponse: {
            msg?: string;
            fileId?: string;
            chunkIndex?: number;
            uploadedChunks?: number;
            totalChunks?: number;
            assembled?: boolean;
            fileReady?: string | null;
        };
        SpeechStreamEvent: {
            /** @enum {string} */
            type?: "partial" | "done" | "error";
            text?: string;
            fileId?: string;
            msg?: string;
        };
        UserProfile: {
            /** @example Codex */
            nickName?: string;
            /** @example https://example.com/avatar.png */
            avatarUrl?: string;
        };
        LoginRequest: {
            /** @description wx.login 返回的临时 code */
            code: string;
            userInfo?: components["schemas"]["UserProfile"];
        };
        H5LoginRequest: {
            /** @description H5 登录账号 */
            username: string;
            /** @description H5 登录密码 */
            password: string;
            userInfo?: components["schemas"]["UserProfile"];
        };
        TokenResponse: {
            token?: string;
            /** @example 登录成功 */
            msg?: string;
        };
        UserInfo: {
            openid?: string;
            username?: string;
            nickname?: string;
            avatarUrl?: string;
            /** @example deepseek-chat */
            model?: string;
            /** Format: date-time */
            lastLogin?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
